branch-defaults:
  dev:
    environment: nevercaution-dev
  master:
    environment: nevercaution-production
global:
  application_name: nevercaution
  default_ec2_keyname: nevercaution-pem
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Java 8 running
    on 64bit Amazon Linux/2.8.3
  default_region: ap-southeast-1
  include_git_submodules: true
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: app.zip