version: 2
jobs:
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      # Prepare
      - run: chmod +x gradlew
      - run:
          name: Install AWS-CLI
          command: |
            sudo apt-get update && sudo apt-get install -y python-setuptools python python-pip
            sudo pip install awsebcli

      # Cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies- # fallback to using the latest cache if no exact match is found
      - run: ./gradlew clean test
      - save_cache:
          paths: ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # AWS Credential
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config

      # Build
      - run:
          name: Build
          command: |
            ./gradlew clean bootJar
            ls -al build/libs
            mv build/libs/sample-0.0.1-SNAPSHOT.jar ./application.jar
            zip -r app.zip application.jar .ebextensions Procfile

      # Deploy
      - run:
          name: Deploy to EB
          command: eb deploy -l app-`git rev-parse HEAD` -m "`git show -s --format=%s HEAD`"

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - dev
                - master